name = "dweb.net"
compatibility_date = "2025-03-22"

[build]
command = "git submodule update --init --recursive && HUGO_VERSION=0.92.2 hugo --gc --minify"
output_dir = "public"

[site]
bucket = "./public" 